---
name: Securin Scan
"on":
- workflow_dispatch
- pull_request
jobs:
  scanning:
    env:
      APP_ID: 23ba3deddc9e88de26bdacf4a776066e24de52636f15b45603c5d3b4a0042de9
    steps:
    - uses: actions/checkout@v2
    - name: Scan Initiated
      run: |-
        docker pull -q shiftleft-cli:latest
        docker run -v ${{github.workspace}}:/src  --volume ${{github.workspace}}:/workdir shiftleft-cli:latest -user ${{ secrets.USER_NAME }} -pass ${{ secrets.PASSWORD }} -app_id ${{ env.APP_ID }} event:${{ github.event_name }}  pr_number:${{ github.event.number }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{github.workspace}}/results/result.sarif
      if: hashFiles('**/result.sarif') !=''
    - name: Evaluate build status
      run: |
        cat ${{github.workspace}}/results/status.txt
        exit 1
      if: hashFiles('**/status.txt') !=''
    runs-on: ubuntu-latest
