---
name: Securin Scan
"on":
- workflow_dispatch
- pull_request
jobs:
  scanning:
    env:
      APP_ID: 23ba3deddc9e88de26bdacf4a776066e24de52636f15b45603c5d3b4a0042de9
    steps:
    - name: Access token
      id: access_token
      run: |-
        token=$( curl --request POST 'http://66ee-103-70-43-178.ngrok.io/resultparserapi/v1/access_token'  --header 'Content-Type: application/json'  --data-raw  '{"userId": "${{ secrets.USER_NAME }}", "password": "${{ secrets.PASSWORD }}" }' | jq -r '.access_token' )
        echo "::set-output name=token::$token"
    - name: Retrieve Scan Info
      id: auth_token
      run: |-
        respJson=$(curl --location --request GET 'http://0471-103-70-43-178.ngrok.io/shiftleftapi/scan-info?app_id=${{ env.APP_ID }}'  --header 'Authorization: Bearer ${{steps.access_token.outputs.token}}'  --data-raw ' ' )
        echo "::set-output name=authTokenJson::$respJson"
    - uses: actions/checkout@v2
    - name: Scan Initiated
      run: |-
        docker login --username  ${{fromJson(steps.auth_token.outputs.authTokenJson).user}} --password ${{fromJson(steps.auth_token.outputs.authTokenJson).password}} ${{fromJson(steps.auth_token.outputs.authTokenJson).proxyUrl}}
        docker pull -q 535827507377.dkr.ecr.us-west-2.amazonaws.com/shiftleft-cli:latest
        docker run -v ${{github.workspace}}:/src  --volume ${{github.workspace}}:/workdir  535827507377.dkr.ecr.us-west-2.amazonaws.com/shiftleft-cli:latest -user ${{ secrets.USER_NAME }} -pass ${{ secrets.PASSWORD }} -app_id ${{ env.APP_ID }} event:${{ github.event_name }}  pr_number:${{ github.event.number }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{github.workspace}}/results/result.sarif
      if: hashFiles('**/result.sarif') !=''
    - name: Evaluate build status
      run: |
        cat ${{github.workspace}}/results/status.txt
        exit 1
      if: hashFiles('**/status.txt') !=''
    runs-on: ubuntu-latest
